---
- hosts: testservers
  user: chandu
  sudo: yes
  tasks:
       - name: Install httpd server
         yum: name=httpd state=installed
       - name: Copy index.html
         copy: src=index.html  dest=/var/www/html/index.html
         notify: start the service
  handlers:
       - name: start the service
         service: name=httpd state=started

