--- 
- hosts: localhost 
  user: root 
  sudo: yes
  tasks: 
       - name: install httpd 
         yum: name=httpd state=installed 
       - name: to start the service 
         service: name=httpd state=started 

