---
- hosts: localhost
  user: chandu
  sudo: yes
  vars:
     keypair: instanceC
     instance_type: t2.micro
     image: ami-14a68671
     region: us-east-2
  tasks:
       - name: install the python pip
         yum: name=python-pip state=installed
       - name: install boto
         command: pip install boto
       - name: launch instance
         ec2:
            key_name: "{{ keypair }}"
            group: default
            instance_type: "{{ instance_type }}"
            image: "{{ image }}"
            wait: true
            count: 1 #default
            count_tag:
                   Name: Ansible-instance
            region: "{{ region }}"
            instance_tags:
                   Name: Ansible-instance
            aws_access_key: AKIAIXY7KFOT3BHQLHGQ
            aws_secret_key: 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
         register: ec2
       - name: print all variables
         debug: var=ec2
#       - name: Add all instance public IPs to host group
#        add_host: hostname={{ item.public_ip }} groups=testservers
#        with_items: "{{ ec2.instance }}"
