---
- hosts: localhost
  user: root
  vars:
     keypair: dansible
     instance_type: t2.micro
     image: ami-14a68671
     region: us-east-2
  tasks:
       - name: launch instance
         ec2:
            key_name: "{{ keypair }}"
            group: default
            instance_type: "{{ instance_type }}"
            image: "{{ image }}"
            wait: true
            region: "{{ region }}"
            aws_access_key: AKIAJDDU64I5KN65P4DQ
            aws_secret_key: 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
         register: ec2
       - name: print all variables
         debug: var=ec2

