---
- hosts: localhost
  user: root
  vars:
  aws_region:
  ec2_id:
  tasks:
  - name: Terminate {{ec2_id}} instance in {{aws_region}}
    local_action:
        module: ec2
        state: 'absent'
        region: '{{aws_region}}'
        instance_ids: '{{ec2_id}}'

