---
- hosts: testservers
  user: chandu
  sudo: yes
  gather_facts: yes
  tasks:
   - name: install java
     yum: name=java-1.8.0-openjdk-src.x86_64 state=installed

   - name: Remove older version of tomcat
     file: path=/usr/local/tomcat state=absent

   - name: Download Tomcat
   #  get_url: url=http://www.us.apache.org/dist/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz dest=/tmp
     local_action: get_url url=http://apache.cs.utah.edu/tomcat/tomcat-8/v8.5.20/bin/apache-tomcat-8.5.20.tar.gz dest=/tmp/


   - name: Extract archive
     #command: chdir=/tmp /bin/tar xvf apache-tomcat-8.0.33.tar.gz
     unarchive: src=/tmp/apache-tomcat-8.5.20.tar.gz dest=/tmp

   - name: Copy tomcat folder
     #command:  mkdir /usr/local/tomcat
     file: name=/usr/local/tomcat state=directory 

   - name: move the directory
     command: mv /tmp/apache-tomcat-8.5.20/ /usr/local/tomcat

   - name: Start Tomcat
     command: nohup  /usr/local/tomcat/apache-tomcat-8.5.20/bin/startup.sh &
     sudo: yes

